### ISSUE TITLE
Not working with Simple World Building Sheets

### ISSUE THREAD

**Issue by pawaller** [illandril/FoundryVTT-sheet5e-lockdown#14]
As GM I see "locked - click to unlock" message in top bar of Character Sheet, but as Player (owner) I am still able to edit all values.
Would be fantastic if this module worked with Simple World Building System as my players are new and will fiddle with attributes!
Thank you.

**Comment by illandril** [comment]
I will consider it, but this will be low on my priority list (and I'm only not outright saying no because Simple World Building is such a simple and stable system). Every single sheet needs to be supported independently, and sheets vary substantially from system to system, meaning adding support for any system other than DnD5e substantially increases the overhead for maintaining this module.

**Comment by illandril** [comment]
I am releasing a separate module for character sheet lock down for Simple World-building: [Illandril's Character Sheet Lockdown (Simple World-Building)](https://github.com/illandril/FoundryVTT-sheet-lockdown-worldbuilding)
