### ISSUE TITLE
[FEATURE] Reduced Title bar text & Chatlog of sheet changes

### ISSUE THREAD

**Issue by KajinStyle** [illandril/FoundryVTT-sheet5e-lockdown#33]
The title bar for NPC/PC sheet seems to open at a set size, making the space on the Title Bar limited. If the phrase: "Unlocked (click to lock)" could be reduced to just "Unlocked" or just the Lock icon, that would reduce the clutter one gets from having too many modules installed. That or an option could be added too that lets you change this from Text&Icon to just Icon, would be great too.

Given that this module isn't secured and chances can be made. Can it be possible to code in an ability to be aware of those changes instead? Either a whisper to the GM or a chatlog saved somewhere to review later.

**Comment by illandril** [comment]
Logging or writing changes to chat would be a substantial effort and it is not something I am willing to add.
If you want to keep a history of character sheets, I recommend you do this through periodic screenshots at the time changes are expected to happen.
If you are concerned about intentional cheating, I recommend you talk with your players and either solve the issue(s) that are causing them to want to cheat or make you think they are cheating - anything I could possibly add in a module could be bypassed, and cheating is just a symptom of a larger issue.

I can add an option to have a smaller "icon only" display for the toggle easily enough though.

**Comment by illandril** [comment]
I added four "Lock Toggle Style" options...
1. Icon, Label, and Help (today's behavior)
2. Icon and Label (Icon plus the short "Locked"/"Unlocked" text, no "Click to...")
3. Label only (just "Locked"/"Unlocked")
4. Icon only

These are client settings, so every player can pick a different style if they want.

**Comment by illandril** [comment]
Note: You will need to close and re-open any character sheets after changing this setting to see a difference.
