### ISSUE TITLE
Lock Traits is over-zealous for TidySheet5e

### ISSUE THREAD

**Issue by dstein766** [illandril/FoundryVTT-sheet5e-lockdown#8]
FVTT 0.7.5
DND5e  0.98
Sheet Lockdown 2.0.2
TidySheet5e 0.2.28

ENABLE Lock Traits in Configure Settings

Expectation: Non-blank Traits will still show on the locked-down sheet
Actual: None of the Traits show (most notably, list of known languages doesn't appear even though it includes "Common, <random other languages>" but applies to all)

Expectation: When any Special Trait has a non-blank value, it should be possible to click on the Special Trait cogwheel and see (but not edit) Special Traits
Actual: Special Traits cogwheel doesn't appear at all.  (I have a character who has a global +2 for Ranged Weapon Attacks which is implemented as a Special Trait adjustment.)

**Comment by illandril** [comment]
Showing the non-Special traits is a bug caused by a change in FVTT 0.7.5 (and there are probably other TidySheet5e compatibility issues caused by the same issue). I'll try to get that fixed soon-ish (hopefully I'll find some free time for that this weekend, but no promises).

Showing non-blank Special Traits is an enhancement that will apply to all Sheets, not just Tidy5e, and is not something I am likely to get to any time soon - I've split that part off into Issue #9.
